export default {
  USERS_FETCH: "USERS_FETCH",
  USERS_FETCH_SUCCESS: "USERS_FETCH_SUCCESS",
  USERS_FETCH_ERROR: "USERS_FETCH_ERROR",
  SORT_PARAMS: "SORT_PARAMS",
  REGISTER_FETCH: "REGISTER_FETCH",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_ERROR: "REGISTER_ERROR",
  REGISTER_RESET: "REGISTER_RESET",
};
